# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-03 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccin_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccin_data',
            name='type_vac',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
